language: csharp
mono: none
dotnet: 2.1.302
before_install:
  - nvm install 8.12.0
install:
  - ./install.sh
script:
  - ./build.sh
deploy:
  provider: azure_web_apps
  skip_cleanup: true
cache:
  directories:
    - ./src/SlowSlothBudget.Web/ClientApp/node_modules