language: csharp
mono: none
dotnet: 2.1.302
script:
  - dotnet build -c Release ./src/SlowSlothBudget.Web.sln
  - dotnet test -c Release ./src/SlowSlothBudget.Web.Test/bin/Release/netcoreapp2.1/SlowSlothBudget.Web.Test.dll