pool:
  vmImage: 'vs2017-win2016'

steps:
- script: npm install
  workingDirectory: ./src/SlowSlothBudget.Web/ClientApp
  displayName: 'Restore npm packages'

- script: dotnet restore ./src/SlowSlothBudget.Web/SlowSlothBudget.Web.csproj
  displayName: 'Restore NuGet packages'

- script: dotnet build -c Release ./src/SlowSlothBudget.Web/SlowSlothBudget.Web.csproj
  displayName: 'Build the project'

- task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: '**/*Test/*.csproj'
    arguments: '--configuration Release'
  displayName: 'Run back-end unit tests'

- script: set CI=true && npm test
  workingDirectory: ./src/SlowSlothBudget.Web/ClientApp
  displayName: 'Run front-end unit tests'

- script: dotnet publish -c Release -o ./publish ./src/SlowSlothBudget.Web/SlowSlothBudget.Web.csproj
  displayName: 'Create project release files'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: './src/SlowSlothBudget.Web/publish'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(System.ArtifactsDirectory)/slowslothbudget.zip'
    replaceExistingArchive: true
  displayName: 'Create release artifact'

- task: AzureRmWebAppDeployment@3
  inputs:
    azureSubscription: 'slowslothbudget'
    WebAppName: 'slowslothbudget'
    Package: $(System.ArtifactsDirectory)/**/*.zip
    RenameFilesFlag: true
    TakeAppOfflineFlag: true
    RemoveAdditionalFilesFlag: true
    ExcludeFilesFromAppDataFlag: true
  displayName: 'Deploy the application'